/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author emili
 */
public class Main extends javax.swing.JFrame {
    
    private database bd = new database("./database.accdb");

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        bd.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_BACKGROUND = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        CB_Juego = new javax.swing.JComboBox<>();
        Juego_BT_Ejecutar = new javax.swing.JButton();
        Juego_BT_Generar = new javax.swing.JButton();
        Juego_TF2_Nombre = new javax.swing.JTextField();
        Juego_TF1_Categoria = new javax.swing.JTextField();
        Juego_TF1_Nombre = new javax.swing.JTextField();
        Juego_TF2_Categoria = new javax.swing.JTextField();
        Juego_TF2_Costo = new javax.swing.JTextField();
        Juego_TF1_Costo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Juego_TB1_ = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Juego_TB2_ = new javax.swing.JTable();
        Juego_SQL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        BT_Archivo = new javax.swing.JMenu();
        MItem_AbrirArchivo = new javax.swing.JMenuItem();
        MItem_ArchivosRecientes = new javax.swing.JMenu();
        ArchivoReciente1 = new javax.swing.JMenuItem();
        ArchivoReciente2 = new javax.swing.JMenuItem();
        ArchivoReciente3 = new javax.swing.JMenuItem();
        ArchivoReciente4 = new javax.swing.JMenuItem();
        ArchivoReciente5 = new javax.swing.JMenuItem();
        MItem_Limpiar = new javax.swing.JMenuItem();
        MItem_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_BACKGROUND.setBackground(new java.awt.Color(51, 51, 51));
        Main_BACKGROUND.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB_Juego.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        CB_Juego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(CB_Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, 40));

        Juego_BT_Ejecutar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Juego_BT_Ejecutar.setText("jButton1");
        jPanel1.add(Juego_BT_Ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 40));

        Juego_BT_Generar.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Juego_BT_Generar.setText("jButton1");
        jPanel1.add(Juego_BT_Generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 230, 40));

        Juego_TF2_Nombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(Juego_TF2_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 260, 40));

        Juego_TF1_Categoria.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(Juego_TF1_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 270, 40));

        Juego_TF1_Nombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(Juego_TF1_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 270, 40));

        Juego_TF2_Categoria.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(Juego_TF2_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 260, 40));

        Juego_TF2_Costo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(Juego_TF2_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 190, 260, 40));

        Juego_TF1_Costo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(Juego_TF1_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 270, 40));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel1.setText("Costo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setText("Categoría");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 60, -1));

        Juego_TB1_.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Juego_TB1_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Costo", "Idiomas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Juego_TB1_);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1000, 150));

        Juego_TB2_.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Juego_TB2_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Costo", "Idiomas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(Juego_TB2_);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1000, 170));

        Juego_SQL.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        Juego_SQL.setText("SQL");
        Juego_SQL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        jPanel1.add(Juego_SQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 266, 620, 50));

        jTabbedPane1.addTab("Juego", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setText("Idioma a Juego");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 110, -1));

        jTextField7.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, 40));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 60, -1));

        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jButton3.setText("jButton1");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 250, 40));

        jButton4.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jButton4.setText("jButton1");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 250, 40));

        jComboBox2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 250, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 600, 450));

        jTabbedPane1.addTab("Idioma", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField8.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 250, 40));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setText("Para");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, -1));

        jTextField9.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 250, 40));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel7.setText("Asunto");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 60, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel8.setText("Mensaje");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 60, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 810, 350));

        jTabbedPane1.addTab("Correos", jPanel3);

        Main_BACKGROUND.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 800));

        BT_Archivo.setText("Archivo");

        MItem_AbrirArchivo.setText("Abrir Archivo");
        BT_Archivo.add(MItem_AbrirArchivo);

        MItem_ArchivosRecientes.setText("Archivos Recientes");

        ArchivoReciente1.setText("ArchivoReciente1");
        MItem_ArchivosRecientes.add(ArchivoReciente1);

        ArchivoReciente2.setText("ArchivoReciente2");
        MItem_ArchivosRecientes.add(ArchivoReciente2);

        ArchivoReciente3.setText("ArchivoReciente3");
        MItem_ArchivosRecientes.add(ArchivoReciente3);

        ArchivoReciente4.setText("ArchivoReciente4");
        MItem_ArchivosRecientes.add(ArchivoReciente4);

        ArchivoReciente5.setText("ArchivoReciente5");
        MItem_ArchivosRecientes.add(ArchivoReciente5);

        BT_Archivo.add(MItem_ArchivosRecientes);

        MItem_Limpiar.setText("Limpiar");
        BT_Archivo.add(MItem_Limpiar);

        MItem_Salir.setText("Salir");
        MItem_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItem_SalirActionPerformed(evt);
            }
        });
        BT_Archivo.add(MItem_Salir);

        MenuBar.add(BT_Archivo);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MItem_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItem_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MItem_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ArchivoReciente1;
    private javax.swing.JMenuItem ArchivoReciente2;
    private javax.swing.JMenuItem ArchivoReciente3;
    private javax.swing.JMenuItem ArchivoReciente4;
    private javax.swing.JMenuItem ArchivoReciente5;
    private javax.swing.JMenu BT_Archivo;
    private javax.swing.JComboBox<String> CB_Juego;
    private javax.swing.JButton Juego_BT_Ejecutar;
    private javax.swing.JButton Juego_BT_Generar;
    private javax.swing.JLabel Juego_SQL;
    private javax.swing.JTable Juego_TB1_;
    private javax.swing.JTable Juego_TB2_;
    private javax.swing.JTextField Juego_TF1_Categoria;
    private javax.swing.JTextField Juego_TF1_Costo;
    private javax.swing.JTextField Juego_TF1_Nombre;
    private javax.swing.JTextField Juego_TF2_Categoria;
    private javax.swing.JTextField Juego_TF2_Costo;
    private javax.swing.JTextField Juego_TF2_Nombre;
    private javax.swing.JMenuItem MItem_AbrirArchivo;
    private javax.swing.JMenu MItem_ArchivosRecientes;
    private javax.swing.JMenuItem MItem_Limpiar;
    private javax.swing.JMenuItem MItem_Salir;
    private javax.swing.JPanel Main_BACKGROUND;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
