/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 *
 * @author emili
 */
public class Registro extends javax.swing.JFrame {

    
    database bd = new database("./database.accdb");
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        bd.conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro_BACKGROUND = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Reg_TF_Usuario = new javax.swing.JTextField();
        Reg_PF_Password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Reg_BT_Registrar = new javax.swing.JButton();
        Reg_TF_Nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Reg_TF_Correo = new javax.swing.JTextField();
        Reg_SP_Edad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registro_BACKGROUND.setBackground(new java.awt.Color(51, 51, 51));
        Registro_BACKGROUND.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        Registro_BACKGROUND.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        Reg_TF_Usuario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Registro_BACKGROUND.add(Reg_TF_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 240, 40));

        Reg_PF_Password.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Registro_BACKGROUND.add(Reg_PF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 240, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 204));
        jLabel3.setText("Registro");
        Registro_BACKGROUND.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        Reg_BT_Registrar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        Reg_BT_Registrar.setText("Registro");
        Reg_BT_Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Reg_BT_RegistrarMousePressed(evt);
            }
        });
        Registro_BACKGROUND.add(Reg_BT_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 230, 50));

        Reg_TF_Nombre.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Registro_BACKGROUND.add(Reg_TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 240, 40));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel4.setText("Nombre");
        Registro_BACKGROUND.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel5.setText("Edad");
        Registro_BACKGROUND.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        Reg_TF_Correo.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        Registro_BACKGROUND.add(Reg_TF_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 240, 40));

        Reg_SP_Edad.setModel(new javax.swing.SpinnerNumberModel(10, 10, 100, 1));
        Registro_BACKGROUND.add(Reg_SP_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 220, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel6.setText("Correo");
        Registro_BACKGROUND.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel7.setText("Usuario");
        Registro_BACKGROUND.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro_BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registro_BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Reg_BT_RegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Reg_BT_RegistrarMousePressed
        
        try{
            boolean val = true;
            bd.query.execute("select usuario from usuarios");
            ResultSet rs = bd.query.getResultSet();
            while(rs.next()){
                if(rs.getString(1).equals(Reg_TF_Usuario.getText())){
                    val = false;
                }
            }
            if(val == false){
                JOptionPane.showMessageDialog(this, "Ingrese un usuario distinto");
            }else{
                if(Reg_TF_Correo.getText().isEmpty() || Reg_TF_Correo.getText().isBlank()){
                    val = false;
                }
                if(String.valueOf(Reg_PF_Password.getPassword()).isBlank() || String.valueOf(Reg_PF_Password.getPassword()).isEmpty()){
                    val = false;
                }
                if(Reg_TF_Nombre.getText().isBlank() || Reg_TF_Nombre.getText().isEmpty()){
                    val = false;
                }
                if(Reg_TF_Usuario.getText().isBlank() || Reg_TF_Usuario.getText().isEmpty()){
                    val = false;
                }
                if(val == true){
                    String contra = LibLab9.encrypt(String.valueOf(Reg_PF_Password.getPassword()));
                    PreparedStatement ps = bd.query.getConnection().prepareStatement("insert into usuarios (usuario,nombre,edad,contra,correo)"
                            + " values (?,?,?,?,?)");
                    ps.setString(1, Reg_TF_Usuario.getText());
                    ps.setString(2, Reg_TF_Nombre.getText());
                    ps.setInt(3, (int)Reg_SP_Edad.getValue());
                    ps.setString(4, contra);
                    ps.setString(5, Reg_TF_Correo.getText());
                    ps.execute();
                    bd.commit();
                    this.dispose();
                }
                    
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_Reg_BT_RegistrarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reg_BT_Registrar;
    private javax.swing.JPasswordField Reg_PF_Password;
    private javax.swing.JSpinner Reg_SP_Edad;
    private javax.swing.JTextField Reg_TF_Correo;
    private javax.swing.JTextField Reg_TF_Nombre;
    private javax.swing.JTextField Reg_TF_Usuario;
    private javax.swing.JPanel Registro_BACKGROUND;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
